"""Demo 6 locomotion profile constants."""

from demo_5.arena import BASE_VELOCITY_LIMITS


PROFILE_VERSION = "6.0"
DIRECTIONAL_SPEED_SCALE = 3.0
VELOCITY_LIMITS = (
    BASE_VELOCITY_LIMITS[0] * DIRECTIONAL_SPEED_SCALE,
    BASE_VELOCITY_LIMITS[1] * DIRECTIONAL_SPEED_SCALE,
    BASE_VELOCITY_LIMITS[2],
)
